#!/usr/bin/php
<?
$ch = curl_init();
$ret = curl_setopt($ch, CURLOPT_URL,            'http://' . $argv[1] . '/?CLODO_MONITORING');
$ret = curl_setopt($ch, CURLOPT_HEADER,         0);
$ret = curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
$ret = curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$ret = curl_setopt($ch, CURLOPT_TIMEOUT,        4);
$ret = curl_exec($ch);
$err = curl_error($ch);

$s = array('s' => 0);

if (empty($ret)) {
    $s['m'] = 'cURL Error: ' . $err;
}
else
{
    $info = curl_getinfo($ch);

    if (empty($info['http_code'])) {
        $s['m'] = 'No HTTP code was returned'; 
    }
    else
    {
        if(in_array($info['http_code'], array(200, 300, 301)))
        {
            $s['s'] = 1;
        }
        $s['m'] = $info['http_code'] . ' ' . http_out($info['http_code']);
    }
}

curl_close($ch);

print implode('|', $s);

function http_out($o)
{
$a = array(
100=>'Continue',
101=>'Switching Protocols',
200=>'OK',
201=>'Created',
202=>'Accepted',
203=>'Non-Authoritative Information',
204=>'No Content',
205=>'Reset Content',
206=>'Partial Content',
300=>'Multiple Choices',
301=>'Moved Permanently',
302=>'Found',
303=>'See Other',
304=>'Not Modified',
305=>'Use Proxy',
306=>'(Unused)',
307=>'Temporary Redirect',
400=>'Bad Request',
401=>'Unauthorized',
402=>'Payment Required',
403=>'Forbidden',
404=>'Not Found',
405=>'Method Not Allowed',
406=>'Not Acceptable',
407=>'Proxy Authentication Required',
408=>'Request Timeout',
409=>'Conflict',
410=>'Gone',
411=>'Length Required',
412=>'Precondition Failed',
413=>'Request Entity Too Large',
414=>'Request-URI Too Long',
415=>'Unsupported Media Type',
416=>'Requested Range Not Satisfiable',
417=>'Expectation Failed',
500=>'Internal Server Error',
501=>'Not Implemented',
502=>'Bad Gateway',
503=>'Service Unavailable',
504=>'Gateway Timeout',
505=>'HTTP Version Not Supported'
);

return $a[$o];
}
